---
- hosts: localhost
  tasks:
    - ec2_instance:
        key_name: default-ec2
        instance_type: t2.micro
        image_id: ami-05c13eab67c5d8861
        region: us-east-1
        #count: 1
        exact_count: 2
        filters:
          "tag:type": http
        vpc_subnet_id: subnet-0d8af823e6e8c05e3
        network:
          assign_public_ip: true
        security_groups: ["http_server_sg"]
        tags: {type: http, Environment: QA}
        wait: yes
      register: ec2_output
    - debug: var=ec2_output